name: Elixir CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Elixir and Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          elixir-version: "1.18.3"
      - name: Install ImageMagick
        run: sudo apt-get install -y -qq imagemagick
      - name: Install dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix test

  lint:
    name: Run Credo Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Elixir and Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          elixir-version: "1.18.3"
      - name: Install dependencies
        run: mix deps.get
      - name: Run Credo
        run: mix credo

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Elixir and Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          elixir-version: "1.18.3"
      - name: Install dependencies
        run: mix deps.get
      - name: Check Formatting
        run: mix format --check-formatted