name: Elixir CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  credo:
    name: Credo Linting
    runs-on: ubuntu-latest
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          elixir-version: "1.18.3"
      - name: Install CA Certificates
        run: sudo apt-get update && sudo apt-get install -y ca-certificates
      - name: Set SSL_CERT_FILE
        run: echo "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt" >> $GITHUB_ENV
      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir
        with:
          elixir-version: "1.18.3"
          otp-version: "27.0"
      - name: Run Credo
        uses: ./.github/actions/run-credo
        with:
          elixir-version: "1.18.3"

  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          elixir-version: "1.18.3"
      - name: Install CA Certificates
        run: sudo apt-get update && sudo apt-get install -y ca-certificates
      - name: Set SSL_CERT_FILE
        run: echo "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt" >> $GITHUB_ENV
      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir
        with:
          elixir-version: "1.18.3"
          otp-version: "27.0"
      - name: Check Formatting
        uses: ./.github/actions/format-check
        with:
          elixir-version: "1.18.3"

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: triptally_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          elixir-version: "1.18.3"
      - name: Install CA Certificates
        run: sudo apt-get update && sudo apt-get install -y ca-certificates
      - name: Set SSL_CERT_FILE
        run: echo "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt" >> $GITHUB_ENV
      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir
        with:
          elixir-version: "1.18.3"
          otp-version: "27.0"
      - name: Run Tests
        uses: ./.github/actions/run-tests
        with:
          elixir-version: "1.18.3"
          postgres-host: "localhost"
          postgres-port: "5432"
