name: Elixir CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
        with:
          elixir-version: "1.16.2" # Elixir version:
          otp-version: "26.0" # OTP version:
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get

  credo:
    name: Credo Linting
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
        with:
          elixir-version: "1.16.2" # Elixir version:
          otp-version: "26.0" # OTP version:
      - name: Run Credo
        run: mix credo

  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
        with:
          elixir-version: "1.16.2" # Elixir version:
          otp-version: "26.0" # OTP version:
      - name: Check Elixir formatting
        run: mix format --check-formatted

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: triptally_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
        with:
          elixir-version: "1.16.2" # Elixir version:
          otp-version: "26.0" # OTP version:
      - name: Wait for Postgres to be ready
        run: until pg_isready -h localhost -p 5432 -U postgres; do echo "Waiting for postgres..."; sleep 1; done
      - name: Run tests
        env:
          MIX_ENV: test
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_NAME: triptally_test
        run: |
          mix ecto.create
          mix ecto.migrate
          mix test
